name: 'Create project'
description: 'Runs create-node-project and performs tests'
inputs:
  options:
    description: 'create-node-app options'
    required: true
  dbConnection:
    description: 'DB_CONNECTION_STRING env var'
    default: 'postgresql://postgres:postgres@localhost:5432/postgres'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Set up node env
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build the project
      run: pnpm run build
      shell: bash

    - name: Create project
      run: node "$GITHUB_WORKSPACE/bin/create-node-app.js" ${{ inputs.options }}
      shell: bash

    - name: Build created project
      working-directory: ./node-app
      run: pnpm run build
      shell: bash

    - name: Run lint
      working-directory: ./node-app
      run: pnpm run ci-lint
      shell: bash

    - name: Run tests
      working-directory: ./node-app
      run: pnpm run ci-test
      shell: bash
      env:
        DB_CONNECTION_STRING: ${{inputs.dbConnection}}

    - name: Run start
      if: ${{ !contains(inputs.options, '--api none') }}
      working-directory: ./node-app
      run: |
        pnpm run start &
        start_pid=$!
        sleep 10
        kill $start_pid
      shell: bash
      env:
        DB_CONNECTION_STRING: ${{inputs.dbConnection}}

    - name: Run start
      if: ${{ contains(inputs.options, '--api none') }}
      working-directory: ./node-app
      shell: bash
      run: pnpm run start
      env:
        DB_CONNECTION_STRING: ${{inputs.dbConnection}}
