name: create-projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: AckeeCZ/create-node-app/.github/workflows/build.yml@main

  create-projects:
    needs: "build"
    strategy:
      fail-fast: false
      matrix:
        create-app-command: ["create-node-app cloudfunctions", "create-node-app cloudrun"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build the project
        run: npm run build

      - name: Run npm link
        run: npm link

      - name: Create project
        run: ${{ matrix.create-app-command }}
      
      - name: Build created project
        working-directory: ./node-app
        run: npm run build
      
      - name: Run lint
        working-directory: ./node-app
        run: npm run ci-lint

      - name: Run tests
        working-directory: ./node-app
        run: npm run ci-test
      
      - name: Run start
        working-directory: ./node-app
        run: |
          if [[ "${{ matrix.create-app-command }}" != "create-node-app cloudfunctions" ]]; then
            npm run start &
            start_pid=$!
            sleep 10
            kill $start_pid
          else
            echo "Skipping 'Run start' for create-node-app cloudfunctions."
          fi