name: create-projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: AckeeCZ/create-node-app/.github/workflows/build.yml@main

  create-projects:
    needs: "build"
    strategy:
      fail-fast: false
      matrix:
        create-app-options: 
         - "--api rest --database none --pipeline cloudrun-gitlab"
         - "--api graphql --database none --pipeline cloudrun-gitlab"
         - "--api rest --database none --pipeline none"
         - "--api none --database none --pipeline cloudrun-gitlab"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: create-node-app
        uses: ./.github/actions/test-create-project
        with:
          options: ${{ matrix.create-app-options }}
      
  create-projects-with-postgres:
    needs: "build"
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        create-app-options: 
         - "--api none --database postgres-knex --pipeline none"
         - "--api rest --database postgres-knex --pipeline cloudrun-gitlab"
         - "--api graphql --database postgres-knex --pipeline cloudrun-gitlab"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: create-node-app
        uses: ./.github/actions/test-create-project
        with:
          options: ${{ matrix.create-app-options }}